{
	"id": "oval:org.debian:def:145754409364510093290152017263873900708",
	"class": "patch",
	"metadata": {
		"title": "DSA-3151-1 python-django",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 7",
			"product": "python-django"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2015-0219",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0219"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2015-0220",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0220"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2015-0221",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0221"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "no info",
			"dsa": "DSA-3151",
			"date": "2015-02-03"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:1691",
								"comment": "python-django DPKG is earlier than 1.4.5-1+deb7u9"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 7 is installed"
			}
		]
	}
}
