{
	"id": "oval:org.debian:def:268088173537926783313309238754262199074",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2024-37891 python-urllib3",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "python-urllib3"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2024-37891",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-37891"
			}
		],
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:30404",
								"comment": "python-urllib3 DPKG is earlier than 0"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
