{
	"id": "oval:org.debian:def:142886314040382492562889639105266587764",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2020-36599 ruby-omniauth",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "ruby-omniauth"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2020-36599",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36599"
			}
		],
		"description": "lib/omniauth/failure_endpoint.rb in OmniAuth before 1.9.2 (and before 2.0) does not escape the message_key value.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:19863",
								"comment": "ruby-omniauth DPKG is earlier than 0"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
