{
	"id": "oval:org.debian:def:49051042813149937589328098327882755609",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2024-0397 python3.9",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "python3.9"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2024-0397",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0397"
			}
		],
		"description": "A defect was discovered in the Python “ssl” module where there is a memory race condition with the ssl.SSLContext methods “cert_store_stats()” and “get_ca_certs()”. The race condition can be triggered if the methods are called at the same time as certificates are loaded into the SSLContext, such as during the TLS handshake with a certificate directory configured. This issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:29442",
								"comment": "python3.9 DPKG is earlier than 3.9.2-1+deb11u2"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
