{
	"id": "oval:org.debian:def:321238723123461321224378158642941485594",
	"class": "patch",
	"metadata": {
		"title": "DSA-4809-1 python-apt",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 10",
			"product": "python-apt"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2020-27351",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-27351"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "no info",
			"dsa": "DSA-4809",
			"date": "2020-12-09"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:28530",
								"comment": "python-apt DPKG is earlier than 1.8.4.2"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 10 is installed"
			}
		]
	}
}
