{
  "id": "oval:org.debian:def:219519287386295489386607694753535836081",
  "class": "vulnerability",
  "metadata": {
    "title": "CVE-2015-3206 pykerberos",
    "affected": {
      "family": "unix",
      "platform": "Debian GNU/Linux 10",
      "product": "pykerberos"
    },
    "reference": [
      {
        "source": "CVE",
        "ref_id": "CVE-2015-3206",
        "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3206"
      }
    ],
    "description": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
    "debian": {}
  },
  "criteria": {
    "operator": "AND",
    "criterias": [
      {
        "operator": "OR",
        "criterias": [
          {
            "operator": "AND",
            "criterions": [
              {
                "test_ref": "oval:org.debian.oval:tst:2",
                "comment": "all architecture"
              },
              {
                "test_ref": "oval:org.debian.oval:tst:8015",
                "comment": "pykerberos DPKG is earlier than 1.1.5-1"
              }
            ]
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:org.debian.oval:tst:1",
        "comment": "Debian 10 is installed"
      }
    ]
  }
}
